### ISSUE TITLE
[UI/Logic] Store user's score

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#14]
As a user, I want to have the ability to submit my score, so I can check it later.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] Input field with "nickname" placeholder is shown.
- [x] Button label "Submit" is shown to the right of the input field.
- [x] When Button is clicked, score and nickname are saved, so it can be accessed later.

### Additional notes
* Follow the UI project from miro.
* Use a hardcoded value of score (or create input field - it will be removed later).
* To save the score and nickname use Local Storage.
* This functionality should be stored in a separate .js file.

**Comment by Urszuja** [comment]
It's marked as done in sprint 2, so I close it for you :)
