### ISSUE TITLE
[API] Fetch quiz questions  

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#28]
As a developer, I want to have a list of questions, so I can use them in the quiz.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] Random questions are retrieved from the API based on Quiz Settings.
- [x] Data from the response is served as an array of Question objects.

### Additional notes

* This functionality should be stored in a separate .js file.
* Use Question class.

**Comment by Urszuja** [comment]
done.
