### ISSUE TITLE
[UI] Main menu buttons

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#35]
### Acceptance criteria
**Verify, consult and update before starting.**

- [x] Main Menu buttons should be replaced with the Button component.
- [x] Koala appears when the mouse is over the button.
- [x] Location should change accordingly.

### Additional notes
* Use Router component

**Comment by Urszuja** [comment]
I did all, however the issue of "hide&seek" koala remains unsolved. Is it to be cleared for this issue or later?

**Comment by Urszuja** [comment]
done.
