### ISSUE TITLE
[Logic] Question randomizer

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#49]
As a user, I want to quiz with the exact number of questions in my quiz. Those questions are random each time I start a new quiz.

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] Exact number of questions is shown (based on the user's input from Quiz settings);
- [x] Questions are random each time the quiz is opened;

### Additional notes
* This functionality should be stored in a separate .js file.
* As an input, an array with all retrieved Questions will be given.

**Comment by Urszuja** [comment]
Done
