### ISSUE TITLE
[Project UI/UX] Adoption page

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#7]
- [x] Find adoption API.
- [x] Create a project of adoption page e.g. one random pet retrieved from API.

**Comment by mngweb** [comment]
- [ ] Sentences from the local database saying various phrases such as 'take me home', 'I'm looking for a home', 'I'm looking for someone to take me' etc. randomly matched to photos or simply permanently inscribed next to photo

**Comment by GRosza** [comment]
https://shibe.online/ - random shiba inu pics 
https://thatcopy.pw/catapi/ - random cats pics
https://alexwohlbruck.github.io/cat-facts/ - random cat facts
