### ISSUE TITLE
[UX] Score filter

### ISSUE THREAD

**Issue by Nefariusek** [Nefariusek/CodersCamp2021.Project.JavaScript#73]
As a user, I want to have the ability to filter scores in the Leaderboard

### Acceptance criteria
**Verify, consult and update before starting.**

- [x] In the leaderboard view, a dropdown appears for the following settings
    * Type (default all)
    * About (default all)
- [x] In the leaderboard view, 2 inputs fields appear where the user can type in a range of questions (default 0 - max).
- [x] Filters work in real-time.
- [x] When the non-default filter is selected, a "Clear" button appears that resets filter values to the default ones.

### Additional notes
* Reuse Button component, implement dropdown component.

**Comment by Urszuja** [comment]
Filters are ready. Need help with:
1. reverting reset button to Button component - bug with removing button
2.  responsive styling (CSS).
